server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: seed-tracing-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seed_tracing_db
    username: root
    password: "&#73andromeda&#73"
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
