CREATE TABLE
    `seed_tracing_db`.`seed_multipliers`
(
    `meta_instance_id`                                 VARCHAR(255) NOT NULL PRIMARY KEY,
    `meta_model_version`                               VARCHAR(10)  NOT NULL,
    `meta_ui_version`                                  VARCHAR(255),
    `meta_submission_date`                             DATETIME(50) NOT NULL,
    `meta_is_complete`                                 BOOLEAN(7) NOT NULL,
    `meta_date_marked_as_complete`                     DATETIME(50) NOT NULL,
    `biodata_note`                                     VARCHAR(255),
    `consent`                                          VARCHAR(3) NOT NULL,
    `first_name`                                       VARCHAR(255) NOT NULL,
    `last_name`                                        VARCHAR(255) NOT NULL,
    `seed_multiplier_sex`                              VARCHAR(7) NOT NULL,
    `date_of_birth`                                    DATE(50)  NOT NULL,
    `farmer_group`                                     VARCHAR(255) NOT NULL,
    `female_members_quantity`                          INTEGER(7)  NOT NULL,
    `male_members_quantity`                            INTEGER(7)  NOT NULL,
    `seed_multiplier_district`                         VARCHAR(255) NOT NULL,
    `seed_multiplier_county`                           VARCHAR(255) NOT NULL,
    `seed_multiplier_subcounty`                        VARCHAR(255) NOT NULL,
    `seed_multiplier_parish`                           VARCHAR(255) NOT NULL,
    `seed_multiplier_village`                          VARCHAR(255) NOT NULL,
    `seed_multiplier_planting_materials_type`          VARCHAR(255) NOT NULL,
    `seed_multiplier_varieties`                        VARCHAR(255) NOT NULL,
    `seed_multiplier_varieties_banana_other`           VARCHAR(255),
    `seed_multiplier_varieties_potatoes_other`         VARCHAR(255),
    `seed_multiplier_planting_materials_tech`          VARCHAR(255) NOT NULL,
    `seed_multiplier_planting_materials_tech_other`    VARCHAR(255),
    `tech_diffusion`                                   VARCHAR(255),
    `trainer_org`                                      VARCHAR(255) NOT NULL,
    `trainer_org_other`                                VARCHAR(255),
    `training_date`                                    DATE(50)  NOT NULL,
    `trained_other_farmers`                            VARCHAR(3) NOT NULL,
    `trainee_repeat`                                   VARCHAR(255),
    `trained_other_groups`                             VARCHAR(3) NOT NULL,
    `group_trainee_repeat`                             VARCHAR(255),
    `trained_group_trained_others`                     VARCHAR(3) NOT NULL,
    `group_trained_others_repeat`                      VARCHAR(255),
    `technology_utilization_rating`                    INTEGER(2),
    `technology_utilization_rating_reason`             VARCHAR(255),
    `tech_uptake`                                      VARCHAR(255),
    `banana_planting_materials_produced`               INTEGER(7)  NOT NULL,
    `potatoes_planting_materials_produced`             INTEGER(7)  NOT NULL,
    `number_of_production_times`                       INTEGER(7)  NOT NULL,
    `individual_buyers_sold_to_per_season`             INTEGER(7)  NOT NULL,
    `average_planting_materials_bought_per_individual` VARCHAR(15) NOT NULL,
    `female_buyers_percentage`                         INTEGER(3)  NOT NULL,
    `female_buyers_average_age`                        INTEGER(3)  NOT NULL,
    `male_buyers_average_age`                          INTEGER(3)  NOT NULL,
    `male_buyers_percentage`                           INTEGER(3)  NOT NULL,
    `selling_points`                                   VARCHAR(255) NOT NULL,
    `annual_production_capacity`                       INTEGER(7)  NOT NULL,
    `annual_production_sold`                           INTEGER(7)  NOT NULL,
    `annual_production_given_away`                     INTEGER(7)  NOT NULL,
    `annual_production_lost`                           INTEGER(7)  NOT NULL,
    `current_planting_materials_stock`                 INTEGER(7)  NOT NULL,
    `instance_id`                                      VARCHAR(255) NOT NULL
);
